DROP TABLE IF EXISTS user_roles;

DROP TABLE IF EXISTS user_books;

DROP TABLE IF EXISTS "user";

DROP TABLE IF EXISTS role;

DROP TABLE IF EXISTS book;


CREATE TABLE "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    userName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE role (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE book (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount INTEGER NOT NULL,
    added_to_stock DATE NOT NULL,
    available BOOLEAN
);

CREATE TABLE user_roles (
    role_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id)
        REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id)
        REFERENCES role(id) ON DELETE CASCADE
);

CREATE TABLE user_books (
    book_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    took_on DATE NOT NULL,
    due_date DATE NOT NULL,
    returned_on DATE,
    FOREIGN KEY (user_id)
        REFERENCES "user"(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id)
        REFERENCES book(id) ON DELETE CASCADE
);
